-- Fictional demonstration data. Amounts are whole PKR.
INSERT INTO wallets VALUES ('w_ayesha_lhr', '03xx-0000000', 'Ayesha (fictional)', 'Lahore', 'full', 'active', '2025-01-15');
INSERT INTO wallet_profiles VALUES ('w_ayesha_lhr', 'ur', 'Groceries and household bills', 'Longstanding customer; occasional family transfers.');
INSERT INTO wallets VALUES ('w_bilal_khi', '03xx-0000001', 'Bilal (fictional)', 'Karachi', 'basic', 'active', '2026-08-28');
INSERT INTO wallet_profiles VALUES ('w_bilal_khi', 'en', 'New wallet', 'No established spending history.');
INSERT INTO wallets VALUES ('w_imran_isb', '03xx-0000002', 'Imran (fictional)', 'Islamabad', 'full', 'active', '2025-11-02');
INSERT INTO wallet_profiles VALUES ('w_imran_isb', 'ur', 'Utility bills', 'Usually pays during the day.');
INSERT INTO wallets VALUES ('w_sara_lhr', '03xx-0000003', 'Sara (fictional)', 'Lahore', 'basic', 'active', '2026-08-20');
INSERT INTO wallet_profiles VALUES ('w_sara_lhr', 'en', 'Personal transfers', 'Recently opened.');
INSERT INTO wallets VALUES ('w_nadia_lhr', '03xx-0000004', 'Nadia (fictional)', 'Lahore', 'basic', 'active', '2026-08-21');
INSERT INTO wallet_profiles VALUES ('w_nadia_lhr', 'ur', 'Personal transfers', 'Recently opened.');
INSERT INTO wallets VALUES ('w_hamza_rwp', '03xx-0000005', 'Hamza (fictional)', 'Rawalpindi', 'full', 'active', '2024-06-01');
INSERT INTO wallet_profiles VALUES ('w_hamza_rwp', 'en', 'Groceries', 'Prior review closed; watchlist remains active.');
INSERT INTO wallets VALUES ('w_filler_01', '03xx-0000006', 'Example Customer 1 (fictional)', 'Karachi', 'full', 'active', '2025-02-01');
INSERT INTO wallet_profiles VALUES ('w_filler_01', 'ur', 'Routine household spending', 'Synthetic padding only.');
INSERT INTO wallets VALUES ('w_filler_02', '03xx-0000007', 'Example Customer 2 (fictional)', 'Lahore', 'full', 'active', '2025-02-01');
INSERT INTO wallet_profiles VALUES ('w_filler_02', 'en', 'Routine household spending', 'Synthetic padding only.');
INSERT INTO wallets VALUES ('w_filler_03', '03xx-0000008', 'Example Customer 3 (fictional)', 'Karachi', 'full', 'active', '2025-02-01');
INSERT INTO wallet_profiles VALUES ('w_filler_03', 'ur', 'Routine household spending', 'Synthetic padding only.');
INSERT INTO wallets VALUES ('w_filler_04', '03xx-0000009', 'Example Customer 4 (fictional)', 'Lahore', 'full', 'active', '2025-02-01');
INSERT INTO wallet_profiles VALUES ('w_filler_04', 'en', 'Routine household spending', 'Synthetic padding only.');
INSERT INTO wallets VALUES ('w_filler_05', '03xx-0000010', 'Example Customer 5 (fictional)', 'Karachi', 'full', 'active', '2025-02-01');
INSERT INTO wallet_profiles VALUES ('w_filler_05', 'ur', 'Routine household spending', 'Synthetic padding only.');
INSERT INTO wallets VALUES ('w_filler_06', '03xx-0000011', 'Example Customer 6 (fictional)', 'Lahore', 'full', 'active', '2025-02-01');
INSERT INTO wallet_profiles VALUES ('w_filler_06', 'en', 'Routine household spending', 'Synthetic padding only.');
INSERT INTO officers VALUES ('off_fraud_01', 'Farah (demo)', 'fraud');
INSERT INTO officers VALUES ('off_care_01', 'Omar (demo)', 'care');
INSERT INTO officer_prefs VALUES ('off_fraud_01', 'tables', 'en', 0);
INSERT INTO officer_prefs VALUES ('off_care_01', 'paragraph', 'en', 1);
